# Generated by Django 4.2.27 on 2026-04-04 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_shippingrule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingrule',
            name='same_city_fee',
        ),
    ]
