# Generated by Django 4.2.27 on 2026-06-21 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_shippingrule_same_city_fee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VAT',
        ),
    ]
