# Generated by Django 4.2.27 on 2026-04-07 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile'),
        ('orders', '0007_remove_orderitem_shipping_fee'),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='logistics_cost',
            new_name='total_shipping',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='margin',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='option',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='tracking_id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address',
            field=models.TextField(default='Unipetrol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='job_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='option_name',
            field=models.CharField(default='Bike', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_address',
            field=models.TextField(default='Users Address'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='platform_margin',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='shipment',
            name='vendor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shipment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='provider',
            field=models.CharField(default='fillUP', max_length=50),
            preserve_default=False,
        ),
    ]
