# Generated by Django 4.2.27 on 2026-04-13 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_rename_logistics_cost_shipment_total_shipping_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='delivery_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pickup_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
