# Generated by Django 4.2.27 on 2026-04-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0003_shipment_weight_alter_shipment_delivery_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('address', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='shipment',
            name='stage',
            field=models.CharField(choices=[('vendor_to_hub', 'Vendor → Hub'), ('hub_to_hub', 'Hub → Hub'), ('hub_to_customer', 'Hub → Customer')], default='vendor_to_hub', max_length=30),
        ),
        migrations.AddField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='shipment',
            name='destination_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destination_shipments', to='logistics.hub'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='origin_hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_shipments', to='logistics.hub'),
        ),
    ]
