# Generated by Django 4.2.27 on 2026-04-14 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_vendor_hub'),
        ('logistics', '0004_hub_shipment_stage_shipment_tracking_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor'),
        ),
    ]
