# Generated by Django 4.2.27 on 2026-06-01 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_vendor_hub'),
        ('logistics', '0006_shippingnegotiation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shipment',
            old_name='job_id',
            new_name='delivery_agent_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='destination_hub',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='option_name',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='origin_hub',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='pickup_address',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='platform_margin',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='shipping_fee',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='total_shipping',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='weight',
        ),
        migrations.AddField(
            model_name='shipment',
            name='current_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_agent_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(default='created', max_length=30),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='tracking_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='vendor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor'),
        ),
    ]
