# Generated by Django 4.2.27 on 2026-06-13 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0007_rename_job_id_shipment_delivery_agent_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='delivery_address',
            field=models.TextField(default='Unipetrol Estate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='pickup_address',
            field=models.TextField(default='Lagos'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='provider',
            field=models.CharField(default='KIWI', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipment',
            name='stage',
            field=models.CharField(default='created', max_length=50),
            preserve_default=False,
        ),
    ]
