# Generated by Django 4.2.27 on 2026-06-14 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0008_shipment_delivered_at_shipment_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shippingoption',
            name='external_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
