# Generated by Django 4.2.27 on 2026-06-14 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0009_shippingoption_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingoption',
            name='provider',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
