# Generated by Django 4.2.27 on 2026-06-14 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0010_alter_shippingoption_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingoption',
            name='delivery_max_days',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='delivery_min_days',
            field=models.IntegerField(null=True),
        ),
    ]
