# Generated by Django 4.2.27 on 2026-06-14 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0011_alter_shippingoption_delivery_max_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingoption',
            name='base_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='shippingoption',
            name='per_kg_fee',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
