# Generated by Django 4.2.27 on 2026-06-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_vendor_hub'),
        ('orders', '0025_remove_order_selected_provider_and_more'),
        ('logistics', '0014_shipment_courier_name_shipment_estimated_delivery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hub',
        ),
        migrations.DeleteModel(
            name='ShippingOption',
        ),
        migrations.DeleteModel(
            name='ShippingProvider',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='shipment',
            name='vendor',
        ),
    ]
