# Generated by Django 4.2.27 on 2026-06-20 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0015_delete_hub_delete_shippingoption_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingNegotiation',
        ),
    ]
