# Generated by Django 4.2.27 on 2026-07-02 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0016_delete_shippingnegotiation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('picked', 'Picked Up'), ('in_transit', 'In Transit'), ('at_hub', 'At Hub'), ('out_for_delivery', 'Out for Delivery'), ('delivered', 'Delivered'), ('failed', 'Failed Delivery')], db_index=True, default='created', max_length=30),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['tracking_id'], name='logistics_s_trackin_58bd94_idx'),
        ),
        migrations.AddIndex(
            model_name='shipment',
            index=models.Index(fields=['status'], name='logistics_s_status_2d3ba5_idx'),
        ),
    ]
