# Generated by Django 4.2.27 on 2026-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0017_alter_shipment_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="Friendly name, e.g. 'Local (0-20 km)'", max_length=100)),
                ('min_km', models.PositiveIntegerField(default=0, help_text='Lower bound of distance band (inclusive, km)')),
                ('max_km', models.PositiveIntegerField(blank=True, help_text='Upper bound (exclusive, km). Leave blank for unlimited.', null=True)),
                ('base_fee', models.DecimalField(decimal_places=2, default=500, help_text='Flat fee charged regardless of distance (N)', max_digits=10)),
                ('rate_per_km', models.DecimalField(decimal_places=4, default=50, help_text='Additional fee per km (N)', max_digits=8)),
                ('weight_rate_per_kg', models.DecimalField(decimal_places=4, default=30, help_text='Extra fee per kg above the free weight threshold (N)', max_digits=8)),
                ('free_weight_kg', models.DecimalField(decimal_places=2, default=1, help_text='Weight (kg) included in base fee at no extra charge', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['min_km'],
            },
        ),
    ]
