# Generated by Django 4.2.27 on 2026-04-01 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='resolved',
            field=models.BooleanField(default=False),
        ),
    ]
