# Generated by Django 4.2.27 on 2026-05-28 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_remove_service_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceRFQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField()),
                ('document', models.FileField(blank=True, null=True, upload_to='rfq_documents/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rfqs', to='services.service')),
            ],
        ),
    ]
