# Generated by Django 4.2.27 on 2026-04-13 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_hub_shipment_stage_shipment_tracking_id_and_more'),
        ('accounts', '0005_vendor_address_vendor_latitude_vendor_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='hub',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.hub'),
        ),
    ]
