# Generated by Django 4.2.27 on 2026-04-14 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_hub_shipment_stage_shipment_tracking_id_and_more'),
        ('accounts', '0006_vendor_hub'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='hub',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistics.hub'),
        ),
    ]
