# Generated by Django 4.2.27 on 2026-06-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vendor',
            name='hub',
        ),
    ]
