# Generated by Django 4.2.27 on 2026-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='coordinates_pending',
            field=models.BooleanField(default=True, help_text='True until lat/lon have been resolved from address'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendor',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='vendor_logos/'),
        ),
    ]
