# Generated by Django 4.2.27 on 2026-04-02 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendorwallet',
            old_name='available_balance',
            new_name='balance',
        ),
    ]
