# Generated by Django 4.2.27 on 2026-04-11 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_vendor_address_vendor_latitude_vendor_longitude_and_more'),
        ('orders', '0010_order_email'),
        ('wallets', '0002_rename_available_balance_vendorwallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallettransaction',
            name='description',
            field=models.TextField(default='credit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallettransaction',
            name='type',
            field=models.CharField(default='credit', max_length=10),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('logistics_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.order')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.vendor')),
            ],
        ),
    ]
