# Generated by Django 4.2.27 on 2026-04-13 00:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_commission_orderitem_commissions'),
        ('wallets', '0003_wallettransaction_description_wallettransaction_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='logistics_profit',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='platform_fee',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='product_amount',
        ),
        migrations.AddField(
            model_name='commission',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='order_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.orderitem'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='type',
            field=models.CharField(choices=[('product', 'Product'), ('shipping', 'Shipping')], default=1, max_length=20),
            preserve_default=False,
        ),
    ]
