# Generated by Django 4.2.27 on 2026-04-13 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_commissions_orderitem_commission'),
        ('wallets', '0004_remove_commission_logistics_profit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='orders.orderitem'),
        ),
    ]
