# Generated by Django 4.2.27 on 2026-04-13 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_commissions_orderitem_commission'),
        ('accounts', '0005_vendor_address_vendor_latitude_vendor_longitude_and_more'),
        ('wallets', '0005_alter_commission_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commission',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='commission',
            name='type',
        ),
        migrations.AddField(
            model_name='commission',
            name='product_commission',
            field=models.DecimalField(decimal_places=2, default=2000, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='shipping_commission',
            field=models.DecimalField(decimal_places=2, default=300, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commission',
            name='total_commission',
            field=models.DecimalField(decimal_places=2, default=13, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='commission',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='accounts.vendor'),
        ),
    ]
