# Generated by Django 4.2.27 on 2026-04-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
