# Generated by Django 4.2.27 on 2026-04-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_productlisting_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=6),
        ),
    ]
