# Generated by Django 4.2.27 on 2026-05-15 01:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_productlisting_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
