# Generated by Django 4.2.27 on 2026-05-27 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_alter_productmedia_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='catalog.category'),
        ),
    ]
