# Generated by Django 4.2.27 on 2026-05-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_productlisting_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='category',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='categories',
            field=models.ManyToManyField(related_name='product_listings', to='catalog.category'),
        ),
    ]
