# Generated by Django 4.2.27 on 2026-05-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_productlisting_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=models.FileField(upload_to='product_media/'),
        ),
    ]
