# Generated by Django 4.2.27 on 2026-06-08 22:45

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_userprofile_user'),
        ('catalog', '0008_alter_category_options_category_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricingrule',
            options={'ordering': ['priority']},
        ),
        migrations.RemoveField(
            model_name='pricingrule',
            name='pricing_type',
        ),
        migrations.RemoveField(
            model_name='productlisting',
            name='final_price',
        ),
        migrations.RemoveField(
            model_name='productmedia',
            name='created_at',
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='name',
            field=models.CharField(default='Lens', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='catalog.productlisting'),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='rule_type',
            field=models.CharField(choices=[('markup_percentage', 'Markup Percentage'), ('markup_fixed', 'Markup Fixed'), ('discount_percentage', 'Discount Percentage'), ('discount_fixed', 'Discount Fixed')], default='MARKUP_PERCENTAGE', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productlisting',
            name='datasheet',
            field=models.FileField(blank=True, null=True, upload_to='datasheets/'),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_negotiable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='lead_time_days',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='manufacturer',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='minimum_order_quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='model_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='technical_specification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='warranty_period_months',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='productmedia',
            name='sort_order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='priority',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='pricingrule',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pricing_rules', to='accounts.vendor'),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='product_media'),
        ),
        migrations.AlterField(
            model_name='productmedia',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video')], max_length=20),
        ),
        migrations.CreateModel(
            name='ProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('value', models.CharField(max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specifications', to='catalog.productlisting')),
            ],
        ),
    ]
