# Generated by Django 4.2.27 on 2026-06-09 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_alter_productmedia_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='product',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='name',
            field=models.CharField(default='name', max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
