# Generated by Django 4.2.27 on 2026-06-10 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_remove_productlisting_product_productlisting_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='units_sold',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
