# Generated by Django 4.2.27 on 2026-06-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_productlisting_units_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='requires_shipping',
            field=models.BooleanField(default=True),
        ),
    ]
