# Generated by Django 4.2.27 on 2026-06-14 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_productlisting_requires_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='shipping_type',
            field=models.CharField(choices=[('none', 'No Shipping'), ('automatic', 'Automatic Shipping'), ('negotiation', 'Shipping Negotiation')], default='automatic', max_length=20),
        ),
    ]
