# Generated by Django 4.2.27 on 2026-06-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_productlisting_shipping_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='fixed_shipping_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
