# Generated by Django 4.2.27 on 2026-06-15 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_productlisting_fixed_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='requires_negotiation',
            field=models.BooleanField(default=False),
        ),
    ]
