# Generated by Django 4.2.27 on 2026-06-21 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_productlisting_requires_negotiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='base_price',
        ),
        migrations.AddField(
            model_name='productlisting',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='supplier_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
