# Generated by Django 4.2.27 on 2026-06-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_productlisting_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlisting',
            name='profit_percentage',
        ),
        migrations.AddField(
            model_name='category',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=5),
        ),
    ]
