# Generated by Django 4.2.27 on 2026-06-21 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_remove_productlisting_profit_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='is_best_seller',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_fast_moving',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_imported',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_limited_stock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productlisting',
            name='is_verified_supplier',
            field=models.BooleanField(default=False),
        ),
    ]
