# Generated by Django 4.2.27 on 2026-06-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0019_productlisting_is_best_seller_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlisting',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='manufacturer',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='productlisting',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['name'], name='catalog_pro_name_3bba2b_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['brand'], name='catalog_pro_brand_c6c7dd_idx'),
        ),
        migrations.AddIndex(
            model_name='productlisting',
            index=models.Index(fields=['manufacturer'], name='catalog_pro_manufac_18a4f8_idx'),
        ),
    ]
