# Generated by Django 4.2.27 on 2026-07-02 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0020_alter_productlisting_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlisting',
            name='cached_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
