# Generated by Django 4.2.27 on 2026-06-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_negotiationrequest_negotiationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequest',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
    ]
