# Generated by Django 4.2.27 on 2026-06-02 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_order_locked_data_alter_order_status'),
        ('cart', '0004_negotiationrequest_admin_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequest',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.order'),
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='negotiationrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('quoted', 'Quoted'), ('accepted', 'Accepted'), ('paid', 'Paid'), ('expired', 'Expired')], default='pending', max_length=20),
        ),
    ]
