# Generated by Django 4.2.27 on 2026-06-18 20:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_negotiationrequest_customer_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequest',
            name='payment_link_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='negotiationrequest',
            name='payment_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
