# Generated by Django 4.2.27 on 2026-06-18 20:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_negotiationrequest_payment_link_expires_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negotiationrequest',
            name='payment_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
