# Generated by Django 4.2.27 on 2026-06-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_negotiationrequest_payment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequest',
            name='cart_signature',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
