# Generated by Django 4.2.27 on 2026-06-20 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_negotiationrequest_cart_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiationrequest',
            name='negotiation_type',
            field=models.CharField(choices=[('cart', 'Cart Negotiation'), ('shipping', 'Shipping Negotiation')], default='cart', max_length=20),
        ),
    ]
