# Generated by Django 4.2.27 on 2026-07-02 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_productlisting_cached_price'),
        ('cart', '0009_negotiationrequest_negotiation_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cartitem',
            unique_together={('cart', 'product_listing')},
        ),
        migrations.AlterUniqueTogether(
            name='negotiationitem',
            unique_together={('negotiation', 'product_listing')},
        ),
    ]
