# Generated by Django 4.2.27 on 2026-05-29 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('client', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('short_description', models.TextField()),
                ('full_description', models.TextField()),
                ('featured_image', models.ImageField(upload_to='projects/')),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing')], default='completed', max_length=20)),
                ('featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
