# Generated by Django 4.2.27 on 2026-06-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('wattage', models.PositiveIntegerField()),
                ('category', models.CharField(blank=True, max_length=50)),
                ('popular', models.BooleanField(default=False)),
            ],
        ),
    ]
