# Generated by Django 4.2.27 on 2026-07-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('battery_type', models.CharField(choices=[('lead', 'Lead Acid'), ('lithium', 'Lithium')], max_length=20)),
                ('voltage', models.FloatField()),
                ('capacity_ah', models.FloatField()),
                ('depth_of_discharge', models.FloatField(help_text='0.5 for lead acid, 0.95 for lithium')),
                ('efficiency', models.FloatField(default=0.9)),
                ('cycles', models.IntegerField(default=3000)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChargeController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('battery_voltage', models.IntegerField()),
                ('max_pv_voltage', models.FloatField()),
                ('max_charge_current', models.FloatField()),
                ('efficiency', models.FloatField(default=0.98)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DesignSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('peak_sun_hours', models.FloatField(default=5)),
                ('performance_ratio', models.FloatField(default=0.75)),
                ('future_expansion', models.FloatField(default=1.2)),
                ('installation_percentage', models.FloatField(default=10)),
                ('profit_percentage', models.FloatField(default=15)),
                ('vat_percentage', models.FloatField(default=7.5)),
            ],
        ),
        migrations.CreateModel(
            name='Inverter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('rated_power', models.FloatField()),
                ('surge_power', models.FloatField()),
                ('dc_voltage', models.IntegerField()),
                ('efficiency', models.FloatField(default=0.95)),
                ('hybrid', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SolarPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('power', models.FloatField()),
                ('vmp', models.FloatField()),
                ('voc', models.FloatField()),
                ('imp', models.FloatField()),
                ('isc', models.FloatField()),
                ('efficiency', models.FloatField(default=0.21)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='appliance',
            name='surge_factor',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='category',
            field=models.CharField(choices=[('lighting', 'Lighting'), ('cooling', 'Cooling'), ('electronics', 'Electronics'), ('kitchen', 'Kitchen'), ('industrial', 'Industrial'), ('other', 'Other')], default='other', max_length=30),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='wattage',
            field=models.FloatField(),
        ),
    ]
