# Generated by Django 4.2.27 on 2026-07-04 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0002_battery_chargecontroller_designsetting_inverter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('accessory_type', models.CharField(choices=[('bolt', 'Bolt'), ('nut', 'Nut'), ('washer', 'Washer'), ('hanger', 'Hanger'), ('rail', 'Rail'), ('lug', 'Cable Lug'), ('gland', 'Cable Gland'), ('connector', 'MC4 Connector'), ('trunking', 'Trunking'), ('conduit', 'Conduit'), ('clamp', 'Panel Clamp'), ('earthing', 'Earthing Material'), ('battery_rack', 'Battery Rack'), ('other', 'Other')], default='other', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BOQItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=300)),
                ('category', models.CharField(choices=[('material', 'Material'), ('labour', 'Labour'), ('transport', 'Transport')], max_length=20)),
                ('unit', models.CharField(default='pcs', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Breaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('breaker_type', models.CharField(choices=[('ac', 'AC Breaker'), ('dc', 'DC Breaker')], max_length=20)),
                ('current_rating', models.FloatField()),
                ('voltage_rating', models.FloatField()),
                ('poles', models.IntegerField()),
                ('breaking_capacity', models.IntegerField(default=6000)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('cable_type', models.CharField(choices=[('pv', 'PV Cable'), ('battery', 'Battery Cable'), ('ac', 'AC Cable'), ('earth', 'Earth Cable')], max_length=20)),
                ('size_mm', models.FloatField()),
                ('ampacity', models.FloatField()),
                ('voltage_rating', models.IntegerField(blank=True, null=True)),
                ('price_per_meter', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fuse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('fuse_type', models.CharField(choices=[('pv', 'PV Fuse'), ('battery', 'Battery Fuse'), ('ac', 'AC Fuse')], max_length=20)),
                ('current_rating', models.FloatField()),
                ('voltage_rating', models.FloatField()),
                ('poles', models.IntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Isolator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('isolator_type', models.CharField(choices=[('ac', 'AC Isolator'), ('dc', 'DC Isolator')], max_length=20)),
                ('current_rating', models.FloatField()),
                ('voltage_rating', models.FloatField()),
                ('poles', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MountingStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('structure_type', models.CharField(choices=[('roof', 'Roof Mount'), ('ground', 'Ground Mount'), ('carport', 'Carport')], max_length=20)),
                ('panel_capacity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SPD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True)),
                ('name', models.CharField(max_length=100)),
                ('spd_type', models.CharField(choices=[('ac', 'AC SPD'), ('dc', 'DC SPD')], max_length=20)),
                ('voltage_rating', models.FloatField()),
                ('protection_level', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
