# Generated by Django 4.2.27 on 2026-07-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0003_accessory_boqitem_breaker_cable_fuse_isolator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='battery_type',
            field=models.CharField(choices=[('lead_acid', 'Lead Acid'), ('lithium', 'Lithium')], max_length=20),
        ),
    ]
