# Generated by Django 4.2.27 on 2026-07-23 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0004_alter_battery_battery_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='load_type',
            field=models.CharField(choices=[('resistive', 'Resistive'), ('motor', 'Motor'), ('compressor', 'Compressor'), ('electronics', 'Electronics'), ('lighting', 'Lighting')], default='resistive', max_length=20),
        ),
        migrations.AddField(
            model_name='appliance',
            name='starting_type',
            field=models.CharField(choices=[('single', 'Starts alone'), ('possible', 'May start together'), ('simultaneous', 'Can start simultaneously')], default='single', max_length=20),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='category',
            field=models.CharField(choices=[('resistive', 'Resistive'), ('motor', 'Motor'), ('compressor', 'Compressor'), ('electronics', 'Electronics'), ('lighting', 'Lighting')], default='other', max_length=30),
        ),
    ]
