# Generated by Django 4.2.27 on 2026-08-02 23:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('solar', '0005_appliance_load_type_appliance_starting_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('client_name', models.CharField(blank=True, max_length=255)),
                ('project_location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('operating_mode', models.CharField(choices=[('off_grid', 'Off Grid'), ('hybrid', 'Hybrid'), ('grid_tied', 'Grid Tied')], default='off_grid', max_length=30)),
                ('peak_sun_hours', models.DecimalField(decimal_places=2, default=5.0, max_digits=5)),
                ('load_result', models.JSONField(blank=True, default=dict)),
                ('voltage_result', models.JSONField(blank=True, default=dict)),
                ('battery_result', models.JSONField(blank=True, default=dict)),
                ('panel_result', models.JSONField(blank=True, default=dict)),
                ('controller_result', models.JSONField(blank=True, default=dict)),
                ('inverter_result', models.JSONField(blank=True, default=dict)),
                ('protection_result', models.JSONField(blank=True, default=dict)),
                ('cable_result', models.JSONField(blank=True, default=dict)),
                ('accessory_result', models.JSONField(blank=True, default=dict)),
                ('boq_result', models.JSONField(blank=True, default=dict)),
                ('pricing_result', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('designed', 'Designed'), ('quoted', 'Quoted'), ('approved', 'Approved'), ('installed', 'Installed'), ('commissioned', 'Commissioned'), ('completed', 'Completed')], default='draft', max_length=30)),
                ('favorite', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solar_designs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solar Design',
                'verbose_name_plural': 'Solar Designs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='battery',
            name='max_charge_current',
            field=models.FloatField(default=220, help_text='Maximum charging current (A)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battery',
            name='max_discharge_current',
            field=models.FloatField(default=220, help_text='Continuous discharge current (A)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='battery',
            name='warranty_years',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='battery',
            name='weight',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('scheduled_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_service_requests', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to='solar.solardesign')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('battery_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('battery_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pv_voltage', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('pv_current', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('inverter_output', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('load_power', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_logs', to='solar.solardesign')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('technician', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=100)),
                ('findings', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('next_service_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='solar.solardesign')),
            ],
        ),
        migrations.CreateModel(
            name='FaultReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fault_reports', to='solar.solardesign')),
                ('reported_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SolarDesignVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('load_result', models.JSONField(default=dict)),
                ('voltage_result', models.JSONField(default=dict)),
                ('battery_result', models.JSONField(default=dict)),
                ('panel_result', models.JSONField(default=dict)),
                ('controller_result', models.JSONField(default=dict)),
                ('inverter_result', models.JSONField(default=dict)),
                ('protection_result', models.JSONField(default=dict)),
                ('cable_result', models.JSONField(default=dict)),
                ('accessory_result', models.JSONField(default=dict)),
                ('boq_result', models.JSONField(default=dict)),
                ('pricing_result', models.JSONField(default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='solar.solardesign')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('design', 'version')},
            },
        ),
    ]
