# Generated by Django 4.2.27 on 2026-08-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0006_solardesign_battery_max_charge_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inverter',
            name='frequency',
            field=models.FloatField(default=50),
        ),
        migrations.AddField(
            model_name='inverter',
            name='output_voltage',
            field=models.FloatField(default=230),
        ),
        migrations.AddField(
            model_name='inverter',
            name='phase',
            field=models.CharField(choices=[('single_phase', 'Single Phase'), ('three_phase', 'Three Phase')], default='single_phase', max_length=20),
        ),
    ]
