# Generated by Django 4.2.27 on 2026-08-15 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0007_inverter_frequency_inverter_output_voltage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='design',
        ),
        migrations.RemoveField(
            model_name='performancelog',
            name='design',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='assigned_to',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='servicerequest',
            name='design',
        ),
        migrations.AlterModelOptions(
            name='solardesign',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='solardesign',
            name='autonomy_days',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='category',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='surge_factor',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AlterField(
            model_name='appliance',
            name='wattage',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='battery',
            name='capacity_ah',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='battery',
            name='cycles',
            field=models.PositiveIntegerField(default=3000),
        ),
        migrations.AlterField(
            model_name='battery',
            name='depth_of_discharge',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='battery',
            name='efficiency',
            field=models.DecimalField(decimal_places=3, default=0.9, max_digits=6),
        ),
        migrations.AlterField(
            model_name='battery',
            name='max_charge_current',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='battery',
            name='max_discharge_current',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='battery',
            name='voltage',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='battery',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='breaking_capacity',
            field=models.PositiveIntegerField(default=6000),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='current_rating',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='poles',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='breaker',
            name='voltage_rating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cable',
            name='ampacity',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cable',
            name='size_mm',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='cable',
            name='voltage_rating',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='chargecontroller',
            name='battery_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='chargecontroller',
            name='efficiency',
            field=models.DecimalField(decimal_places=3, default=0.98, max_digits=6),
        ),
        migrations.AlterField(
            model_name='chargecontroller',
            name='max_charge_current',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='chargecontroller',
            name='max_pv_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='designsetting',
            name='future_expansion',
            field=models.DecimalField(decimal_places=3, default=1.2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='designsetting',
            name='installation_percentage',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=6),
        ),
        migrations.AlterField(
            model_name='designsetting',
            name='peak_sun_hours',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='designsetting',
            name='performance_ratio',
            field=models.DecimalField(decimal_places=3, default=0.75, max_digits=6),
        ),
        migrations.AlterField(
            model_name='designsetting',
            name='profit_percentage',
            field=models.DecimalField(decimal_places=2, default=15, max_digits=6),
        ),
        migrations.AlterField(
            model_name='designsetting',
            name='vat_percentage',
            field=models.DecimalField(decimal_places=2, default=7.5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='fuse',
            name='current_rating',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='fuse',
            name='poles',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='fuse',
            name='voltage_rating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='dc_voltage',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='efficiency',
            field=models.DecimalField(decimal_places=3, default=0.95, max_digits=6),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='frequency',
            field=models.DecimalField(decimal_places=2, default=50, max_digits=6),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='output_voltage',
            field=models.DecimalField(decimal_places=2, default=230, max_digits=8),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='rated_power',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inverter',
            name='surge_power',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='isolator',
            name='current_rating',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='isolator',
            name='poles',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='isolator',
            name='voltage_rating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mountingstructure',
            name='panel_capacity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='solardesign',
            name='peak_sun_hours',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=6),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='efficiency',
            field=models.DecimalField(decimal_places=3, default=0.21, max_digits=6),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='imp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='isc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='power',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='vmp',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='solarpanel',
            name='voc',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='spd',
            name='voltage_rating',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.DeleteModel(
            name='FaultReport',
        ),
        migrations.DeleteModel(
            name='MaintenanceRecord',
        ),
        migrations.DeleteModel(
            name='PerformanceLog',
        ),
        migrations.DeleteModel(
            name='ServiceRequest',
        ),
    ]
