# Generated by Django 4.2.27 on 2026-08-21 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0010_solardesign_warnings_result_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
        migrations.DeleteModel(
            name='Battery',
        ),
        migrations.DeleteModel(
            name='Breaker',
        ),
        migrations.DeleteModel(
            name='Cable',
        ),
        migrations.DeleteModel(
            name='ChargeController',
        ),
        migrations.DeleteModel(
            name='Fuse',
        ),
        migrations.DeleteModel(
            name='Inverter',
        ),
        migrations.DeleteModel(
            name='Isolator',
        ),
        migrations.DeleteModel(
            name='MountingStructure',
        ),
        migrations.DeleteModel(
            name='SolarPanel',
        ),
        migrations.DeleteModel(
            name='SPD',
        ),
    ]
