# Generated by Django 4.2.27 on 2026-08-30 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0021_productlisting_cached_price'),
        ('solar', '0011_delete_accessory_delete_battery_delete_breaker_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='batteryspecification',
            name='hybrid_compatible',
            field=models.BooleanField(default=False, help_text='Suitable for use with a hybrid inverter system.'),
        ),
        migrations.AddField(
            model_name='solardesign',
            name='installation_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('industrial', 'Industrial / Commercial')], default='residential', max_length=20),
        ),
        migrations.CreateModel(
            name='SolarGeneratorSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battery_capacity_kwh', models.DecimalField(decimal_places=2, max_digits=8)),
                ('inverter_rated_power', models.DecimalField(decimal_places=2, max_digits=12)),
                ('inverter_surge_power', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('output_voltage', models.DecimalField(decimal_places=2, default=230, max_digits=8)),
                ('phase', models.CharField(choices=[('single_phase', 'Single Phase'), ('three_phase', 'Three Phase')], default='single_phase', max_length=20)),
                ('hybrid', models.BooleanField(default=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='solar_generator_spec', to='catalog.productlisting')),
            ],
        ),
    ]
