# Generated by Django 4.2.27 on 2026-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solar', '0012_batteryspecification_hybrid_compatible_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appliance',
            name='installation_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('industrial', 'Industrial / Commercial')], db_index=True, default='residential', help_text='Where this typical appliance load is normally used.', max_length=20),
        ),
    ]
