# Generated by Django 4.2.27 on 2026-08-31
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [("solar", "0014_seed_residential_and_industrial_appliances")]
    operations = [migrations.CreateModel(
        name="EarthingDesign",
        fields=[
            ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
            ("project_name", models.CharField(max_length=255)),
            ("installation_type", models.CharField(default="industrial", max_length=30)),
            ("standard", models.CharField(blank=True, max_length=100)),
            ("inputs", models.JSONField(default=dict)),
            ("result", models.JSONField(default=dict)),
            ("created_at", models.DateTimeField(auto_now_add=True)),
            ("updated_at", models.DateTimeField(auto_now=True)),
            ("solar_design", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="earthing_assessments", to="solar.solardesign")),
            ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="earthing_designs", to=settings.AUTH_USER_MODEL)),
        ], options={"ordering": ("-updated_at",)},
    )]