# Generated by Django 4.2.27 on 2026-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_received_orderitem_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('same_city_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('same_state_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('interstate_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
