# Generated by Django 4.2.27 on 2026-04-03 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_shippingrule'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShippingRule',
        ),
    ]
