# Generated by Django 4.2.27 on 2026-04-07 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orderitem_delivery_end_orderitem_delivery_start_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='shipping_fee',
        ),
    ]
