# Generated by Django 4.2.27 on 2026-04-10 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_orderitem_shipping_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
