# Generated by Django 4.2.27 on 2026-04-11 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_billing_address_order_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(default='flare@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
