# Generated by Django 4.2.27 on 2026-04-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='locked_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
