# Generated by Django 4.2.27 on 2026-04-13 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_order_locked_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='commission',
            new_name='commissions',
        ),
    ]
