# Generated by Django 4.2.27 on 2026-04-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_rename_commission_orderitem_commissions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='commissions',
            new_name='commission',
        ),
    ]
