# Generated by Django 4.2.27 on 2026-04-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_rename_commissions_orderitem_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(default='Unipetrol'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(default='Zenith Estate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='locked_data',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
