# Generated by Django 4.2.27 on 2026-04-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_order_delivery_address_order_pickup_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_address',
        ),
        migrations.AlterField(
            model_name='order',
            name='locked_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
