# Generated by Django 4.2.27 on 2026-04-14 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('orders', '0015_remove_order_delivery_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_city',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.state'),
            preserve_default=False,
        ),
    ]
