# Generated by Django 4.2.27 on 2026-06-14 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_order_shipping_fee_order_shipping_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='requires_shipping_negotiation',
            field=models.BooleanField(default=True),
        ),
    ]
