# Generated by Django 4.2.27 on 2026-06-15 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_order_requires_shipping_negotiation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='selected_provider',
        ),
        migrations.RemoveField(
            model_name='order',
            name='selected_shipping_option',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_provider',
        ),
    ]
