# Generated by Django 4.2.27 on 2026-06-21 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_negotiationrequest_negotiation_type'),
        ('orders', '0025_remove_order_selected_provider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='negotiation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.negotiationrequest'),
        ),
    ]
