# solar/services/warning_engine.py

"""
Solar PV Warning and Validation Engine.

Phase
-----
Final engineering validation stage after:

    Load
        ↓
    System Voltage
        ↓
    Battery
        ↓
    Panel / PV
        ↓
    Charge Controller
        ↓
    Inverter
        ↓
    Protection
        ↓
    Cable
        ↓
    Accessories
        ↓
    BOQ
        ↓
    Pricing
        ↓
    Warnings / Validation

Responsibilities
----------------
This engine:

    - collects warnings generated by upstream engines
    - performs cross-engine validation
    - identifies missing or unsuccessful stages
    - checks important electrical relationships
    - checks battery/system-voltage consistency
    - checks PV/controller compatibility
    - checks inverter/load compatibility
    - checks cable/protection consistency where data is available
    - checks BOQ completeness
    - checks pricing completeness
    - provides a final engineering readiness status

This engine DOES NOT:
    - resize equipment
    - select products
    - change upstream results
    - calculate pricing
    - replace individual engineering engines

The engine is deliberately tolerant of optional fields because
different engineering engines expose different levels of detail.
"""

from __future__ import annotations

from decimal import Decimal, InvalidOperation
from typing import Any, Dict, Iterable, List, Optional


# ======================================================================
# CONSTANTS
# ======================================================================

ENGINE_NAME = "Warning and Validation Engine"
ENGINE_VERSION = "1.0.0"

ZERO = Decimal("0")
ONE = Decimal("1")

SEVERITY_CRITICAL = "critical"
SEVERITY_ERROR = "error"
SEVERITY_WARNING = "warning"
SEVERITY_ADVISORY = "advisory"
SEVERITY_INFO = "info"

VALID_SEVERITIES = {
    SEVERITY_CRITICAL,
    SEVERITY_ERROR,
    SEVERITY_WARNING,
    SEVERITY_ADVISORY,
    SEVERITY_INFO,
}

# Engineering thresholds used only for validation/warning purposes.
MIN_BATTERY_DOD = Decimal("0.50")
MAX_BATTERY_DOD = Decimal("1.00")

MIN_INVERTER_EFFICIENCY = Decimal("0.80")
MAX_INVERTER_EFFICIENCY = Decimal("1.00")

MAX_BATTERY_BANK_VOLTAGE_ERROR_PERCENT = Decimal("10")

MIN_PV_MARGIN = Decimal("1.00")
MIN_CONTROLLER_MARGIN = Decimal("1.00")

# Very large quantities are not automatically invalid, but should
# receive an engineering review.
MAX_REASONABLE_BATTERY_QUANTITY = 24
MAX_REASONABLE_PANEL_QUANTITY = 100
MAX_REASONABLE_PARALLEL_STRINGS = 8


# ======================================================================
# DECIMAL / GENERAL HELPERS
# ======================================================================

def _decimal(
    value: Any,
    default: Decimal = ZERO,
) -> Decimal:
    """Safely convert a value to Decimal."""

    if value is None:
        return default

    if isinstance(value, Decimal):
        return value

    try:
        return Decimal(str(value))
    except (
        InvalidOperation,
        ValueError,
        TypeError,
    ):
        return default


def _positive(
    value: Any,
) -> Optional[Decimal]:
    """Return a positive Decimal or None."""

    number = _decimal(value)

    if number <= ZERO:
        return None

    return number


def _first(
    mapping: Any,
    *keys: str,
    default: Any = None,
) -> Any:
    """
    Return the first non-None value from a dictionary.

    This deliberately supports aliases used by the different
    engineering result contracts.
    """

    if not isinstance(mapping, dict):
        return default

    for key in keys:
        value = mapping.get(key)

        if value is not None:
            return value

    return default


def _nested(
    mapping: Any,
    section: str,
    *keys: str,
    default: Any = None,
) -> Any:
    """Read a value from a nested result section."""

    if not isinstance(mapping, dict):
        return default

    nested = mapping.get(section)

    if not isinstance(nested, dict):
        return default

    return _first(
        nested,
        *keys,
        default=default,
    )


def _success(
    result: Any,
) -> bool:
    """Determine whether an engine result reports success."""

    if not isinstance(result, dict):
        return False

    return bool(
        result.get(
            "success",
            result.get(
                "status"
            ) in {
                "ok",
                "calculated",
                "success",
                "complete",
                "completed",
            },
        )
    )


def _warning_list(
    result: Any,
) -> List[Any]:
    """Extract warnings from an engine result."""

    if not isinstance(result, dict):
        return []

    warnings = result.get("warnings", [])

    if warnings is None:
        return []

    if isinstance(warnings, str):
        return [warnings]

    if isinstance(warnings, (list, tuple)):
        return list(warnings)

    return []


def _as_text(
    value: Any,
) -> str:
    """Convert a warning/message to clean text."""

    if isinstance(value, str):
        return value.strip()

    if isinstance(value, dict):
        message = value.get(
            "message",
            value.get(
                "text",
                value.get(
                    "description",
                    "",
                ),
            ),
        )

        if message:
            return str(message).strip()

    return str(value).strip()


# ======================================================================
# WARNING RECORD
# ======================================================================

def _warning(
    code: str,
    severity: str,
    message: str,
    *,
    category: str,
    source: str,
    recommendation: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Create one standardized warning record.

    The record remains template/JSON friendly.
    """

    if severity not in VALID_SEVERITIES:
        severity = SEVERITY_WARNING

    result = {
        "code": str(code),
        "severity": severity,
        "category": str(category),
        "source": str(source),
        "message": str(message),
    }

    if recommendation:
        result["recommendation"] = str(
            recommendation
        )

    return result


# ======================================================================
# RESULT NORMALIZATION
# ======================================================================

def _normalize_warning(
    value: Any,
    source: str,
) -> Dict[str, Any]:
    """
    Normalize an upstream warning.

    Existing engines may return simple strings while future engines
    may return structured warning dictionaries.
    """

    if isinstance(value, dict):

        code = value.get(
            "code",
            "UPSTREAM_WARNING",
        )

        severity = value.get(
            "severity",
            SEVERITY_WARNING,
        )

        category = value.get(
            "category",
            "engineering",
        )

        message = value.get(
            "message",
            value.get(
                "text",
                value.get(
                    "description",
                    "",
                ),
            ),
        )

        recommendation = value.get(
            "recommendation"
        )

        return _warning(
            code=code,
            severity=severity,
            message=str(message),
            category=category,
            source=value.get(
                "source",
                source,
            ),
            recommendation=recommendation,
        )

    return _warning(
        code="UPSTREAM_WARNING",
        severity=SEVERITY_WARNING,
        message=_as_text(value),
        category="engineering",
        source=source,
    )


def _collect_upstream_warnings(
    results: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """
    Collect warnings generated by all completed engines.
    """

    source_map = (
        ("load_result", "Load Engine"),
        ("voltage_result", "System Voltage Engine"),
        ("battery_result", "Battery Engine"),
        ("panel_result", "Panel Engine"),
        ("controller_result", "Charge Controller Engine"),
        ("inverter_result", "Inverter Engine"),
        ("protection_result", "Protection Engine"),
        ("cable_result", "Cable Engine"),
        ("accessory_result", "Accessories Engine"),
        ("boq_result", "BOQ Engine"),
        ("pricing_result", "Pricing Engine"),
    )

    warnings = []

    for result_key, source in source_map:

        result = results.get(result_key)

        for item in _warning_list(result):
            warnings.append(
                _normalize_warning(
                    item,
                    source,
                )
            )

    return warnings


# ======================================================================
# STAGE VALIDATION
# ======================================================================

def _validate_stage_results(
    results: Dict[str, Any],
) -> List[Dict[str, Any]]:
    """
    Validate that every required engineering stage completed.
    """

    checks = (
        ("load_result", "Load Engine"),
        ("voltage_result", "System Voltage Engine"),
        ("battery_result", "Battery Engine"),
        ("panel_result", "Panel Engine"),
        ("controller_result", "Charge Controller Engine"),
        ("inverter_result", "Inverter Engine"),
        ("protection_result", "Protection Engine"),
        ("cable_result", "Cable Engine"),
        ("accessory_result", "Accessories Engine"),
        ("boq_result", "BOQ Engine"),
        ("pricing_result", "Pricing Engine"),
    )

    warnings = []

    for result_key, source in checks:

        result = results.get(result_key)

        if result is None:
            warnings.append(
                _warning(
                    code=f"MISSING_{result_key.upper()}",
                    severity=SEVERITY_CRITICAL,
                    message=(
                        f"{source} result is missing from the "
                        "design pipeline."
                    ),
                    category="pipeline",
                    source=ENGINE_NAME,
                    recommendation=(
                        f"Run the {source} before finalizing "
                        "the solar design."
                    ),
                )
            )
            continue

        if not isinstance(result, dict):
            warnings.append(
                _warning(
                    code=f"INVALID_{result_key.upper()}",
                    severity=SEVERITY_CRITICAL,
                    message=(
                        f"{source} returned an invalid result "
                        "type."
                    ),
                    category="pipeline",
                    source=ENGINE_NAME,
                )
            )
            continue

        if not _success(result):
            message = result.get(
                "message",
                f"{source} did not complete successfully.",
            )

            warnings.append(
                _warning(
                    code=f"FAILED_{result_key.upper()}",
                    severity=SEVERITY_CRITICAL,
                    message=str(message),
                    category="pipeline",
                    source=ENGINE_NAME,
                    recommendation=(
                        f"Resolve the {source} failure before "
                        "using the final design."
                    ),
                )
            )

    return warnings


# ======================================================================
# LOAD VALIDATION
# ======================================================================

def _validate_load(
    result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    calculations = result.get(
        "calculations",
        {},
    )

    daily_energy = _first(
        calculations,
        "daily_energy_wh",
        default=_first(
            result,
            "daily_energy_wh",
            default=ZERO,
        ),
    )

    connected_load = _first(
        calculations,
        "connected_load_w",
        "load_watts",
        default=_first(
            result,
            "load_watts",
            default=ZERO,
        ),
    )

    peak_load = _first(
        calculations,
        "peak_design_load_w",
        "peak_load_w",
        "surge_peak_load_w",
        default=connected_load,
    )

    daily_energy = _decimal(
        daily_energy
    )

    connected_load = _decimal(
        connected_load
    )

    peak_load = _decimal(
        peak_load
    )

    if daily_energy <= ZERO:
        warnings.append(
            _warning(
                code="LOAD_ZERO_ENERGY",
                severity=SEVERITY_CRITICAL,
                message=(
                    "Daily energy consumption is zero or "
                    "missing."
                ),
                category="load",
                source=ENGINE_NAME,
                recommendation=(
                    "Review appliance quantities and operating "
                    "hours."
                ),
            )
        )

    if connected_load <= ZERO:
        warnings.append(
            _warning(
                code="LOAD_ZERO_POWER",
                severity=SEVERITY_CRITICAL,
                message=(
                    "Connected load is zero or missing."
                ),
                category="load",
                source=ENGINE_NAME,
            )
        )

    if peak_load < connected_load:
        warnings.append(
            _warning(
                code="LOAD_PEAK_BELOW_CONNECTED",
                severity=SEVERITY_ERROR,
                message=(
                    "Calculated design peak load is below the "
                    "connected load."
                ),
                category="load",
                source=ENGINE_NAME,
                recommendation=(
                    "Review the load and surge calculations."
                ),
            )
        )

    return warnings


# ======================================================================
# SYSTEM VOLTAGE VALIDATION
# ======================================================================

def _validate_voltage(
    voltage_result: Dict[str, Any],
    battery_result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    system_voltage = _first(
        voltage_result,
        "system_voltage",
        "selected_voltage",
        "recommended_system_voltage",
        default=None,
    )

    if system_voltage is None:
        system_voltage = _nested(
            voltage_result,
            "required",
            "system_voltage",
            "nominal_system_voltage",
        )

    voltage = _positive(
        system_voltage
    )

    if voltage is None:
        warnings.append(
            _warning(
                code="SYSTEM_VOLTAGE_MISSING",
                severity=SEVERITY_CRITICAL,
                message=(
                    "A valid system voltage was not produced."
                ),
                category="voltage",
                source=ENGINE_NAME,
            )
        )

        return warnings

    battery_selected = (
        battery_result.get("selected")
        if isinstance(
            battery_result,
            dict,
        )
        else None
    )

    battery_voltage = None

    if isinstance(
        battery_selected,
        dict,
    ):
        battery_voltage = _first(
            battery_selected,
            "voltage",
            "nominal_voltage",
            "battery_voltage",
            default=None,
        )

    if battery_voltage is None:
        battery_voltage = _nested(
            battery_result,
            "selected",
            "voltage",
            "nominal_voltage",
            "battery_voltage",
        )

    if battery_voltage is not None:

        battery_voltage_decimal = _positive(
            battery_voltage
        )

        if battery_voltage_decimal:

            series = _first(
                battery_selected or {},
                "series",
                "series_count",
                default=None,
            )

            if series is None:
                series = _nested(
                    battery_result,
                    "configuration",
                    "series",
                    "series_count",
                )

            if series is not None:

                actual_bank_voltage = (
                    battery_voltage_decimal
                    * _decimal(series)
                )

                if voltage > ZERO:

                    error_percent = (
                        abs(
                            actual_bank_voltage
                            - voltage
                        )
                        / voltage
                        * Decimal("100")
                    )

                    if (
                        error_percent
                        >
                        MAX_BATTERY_BANK_VOLTAGE_ERROR_PERCENT
                    ):
                        warnings.append(
                            _warning(
                                code=(
                                    "BATTERY_BANK_VOLTAGE_MISMATCH"
                                ),
                                severity=SEVERITY_ERROR,
                                message=(
                                    "The actual nominal battery-bank "
                                    "voltage differs materially from "
                                    "the selected system voltage."
                                ),
                                category="voltage",
                                source=ENGINE_NAME,
                                recommendation=(
                                    "Verify battery series "
                                    "configuration and inverter "
                                    "DC-voltage compatibility."
                                ),
                            )
                        )

    return warnings


# ======================================================================
# BATTERY VALIDATION
# ======================================================================

def _validate_battery(
    result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    requirement = result.get(
        "requirement",
        {},
    )

    selected = result.get(
        "selected",
        {},
    )

    if not isinstance(
        requirement,
        dict,
    ):
        requirement = {}

    if not isinstance(
        selected,
        dict,
    ):
        selected = {}

    required_energy = _decimal(
        _first(
            requirement,
            "required_energy_wh",
            "required_energy",
            default=ZERO,
        )
    )

    usable_energy = _decimal(
        _first(
            selected,
            "usable_energy",
            "usable_energy_wh",
            default=ZERO,
        )
    )

    if (
        required_energy > ZERO
        and
        usable_energy > ZERO
        and
        usable_energy < required_energy
    ):
        warnings.append(
            _warning(
                code="BATTERY_ENERGY_SHORTFALL",
                severity=SEVERITY_CRITICAL,
                message=(
                    "Selected battery-bank usable energy is "
                    "below the calculated requirement."
                ),
                category="battery",
                source=ENGINE_NAME,
                recommendation=(
                    "Increase battery-bank capacity or review "
                    "the design assumptions."
                ),
            )
        )

    dod = _first(
        requirement,
        "depth_of_discharge",
        "dod",
        default=None,
    )

    if dod is not None:

        dod_decimal = _decimal(dod)

        if (
            dod_decimal < MIN_BATTERY_DOD
            or
            dod_decimal > MAX_BATTERY_DOD
        ):
            warnings.append(
                _warning(
                    code="BATTERY_DOD_OUT_OF_RANGE",
                    severity=SEVERITY_ERROR,
                    message=(
                        "Battery depth of discharge is outside "
                        "the expected engineering range."
                    ),
                    category="battery",
                    source=ENGINE_NAME,
                    recommendation=(
                        "Verify the battery manufacturer's "
                        "recommended operating limits."
                    ),
                )
            )

    quantity = _first(
        selected,
        "quantity",
        "total_quantity",
        default=None,
    )

    if quantity is not None:

        try:
            quantity_int = int(quantity)
        except (
            TypeError,
            ValueError,
        ):
            quantity_int = 0

        if quantity_int <= 0:
            warnings.append(
                _warning(
                    code="BATTERY_ZERO_QUANTITY",
                    severity=SEVERITY_CRITICAL,
                    message=(
                        "No valid battery quantity was selected."
                    ),
                    category="battery",
                    source=ENGINE_NAME,
                )
            )

        elif (
            quantity_int
            >
            MAX_REASONABLE_BATTERY_QUANTITY
        ):
            warnings.append(
                _warning(
                    code="BATTERY_LARGE_BANK",
                    severity=SEVERITY_ADVISORY,
                    message=(
                        "The selected battery bank contains a "
                        "large number of individual batteries."
                    ),
                    category="battery",
                    source=ENGINE_NAME,
                    recommendation=(
                        "Review series/parallel architecture, "
                        "battery current sharing and installation "
                        "requirements."
                    ),
                )
            )

    parallel = _first(
        selected,
        "parallel",
        "parallel_count",
        default=None,
    )

    if parallel is not None:

        try:
            parallel_int = int(parallel)
        except (
            TypeError,
            ValueError,
        ):
            parallel_int = 0

        if (
            parallel_int
            >
            MAX_REASONABLE_PARALLEL_STRINGS
        ):
            warnings.append(
                _warning(
                    code="BATTERY_EXCESSIVE_PARALLEL_STRINGS",
                    severity=SEVERITY_WARNING,
                    message=(
                        "The battery bank requires a high number "
                        "of parallel strings."
                    ),
                    category="battery",
                    source=ENGINE_NAME,
                    recommendation=(
                        "Review battery-bank architecture and "
                        "consider a higher-capacity battery unit "
                        "or alternative system architecture."
                    ),
                )
            )

    return warnings


# ======================================================================
# PV / PANEL VALIDATION
# ======================================================================

def _validate_panel(
    result: Dict[str, Any],
    controller_result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    selected = result.get(
        "selected",
        {},
    )

    requirement = result.get(
        "requirement",
        {},
    )

    if not isinstance(
        selected,
        dict,
    ):
        selected = {}

    if not isinstance(
        requirement,
        dict,
    ):
        requirement = {}

    array_power = _decimal(
        _first(
            selected,
            "array_power",
            "array_power_w",
            "pv_power",
            default=_first(
                requirement,
                "array_power",
                "minimum_pv_power",
                default=ZERO,
            ),
        )
    )

    required_power = _decimal(
        _first(
            requirement,
            "required_pv_power",
            "minimum_pv_power",
            default=ZERO,
        )
    )

    if (
        required_power > ZERO
        and
        array_power > ZERO
        and
        array_power < required_power
    ):
        warnings.append(
            _warning(
                code="PV_ARRAY_UNDERSIZED",
                severity=SEVERITY_CRITICAL,
                message=(
                    "The selected PV array power is below the "
                    "calculated minimum PV requirement."
                ),
                category="pv",
                source=ENGINE_NAME,
                recommendation=(
                    "Increase the PV array capacity or review "
                    "the PV design assumptions."
                ),
            )
        )

    panel_quantity = _first(
        selected,
        "quantity",
        "panel_quantity",
        "total_panels",
        default=None,
    )

    if panel_quantity is not None:

        try:
            panel_count = int(
                panel_quantity
            )
        except (
            TypeError,
            ValueError,
        ):
            panel_count = 0

        if panel_count <= 0:
            warnings.append(
                _warning(
                    code="PV_ZERO_PANEL_QUANTITY",
                    severity=SEVERITY_CRITICAL,
                    message=(
                        "No valid PV panel quantity was selected."
                    ),
                    category="pv",
                    source=ENGINE_NAME,
                )
            )

        elif (
            panel_count
            >
            MAX_REASONABLE_PANEL_QUANTITY
        ):
            warnings.append(
                _warning(
                    code="PV_LARGE_ARRAY",
                    severity=SEVERITY_ADVISORY,
                    message=(
                        "The selected PV array contains a large "
                        "number of modules."
                    ),
                    category="pv",
                    source=ENGINE_NAME,
                    recommendation=(
                        "Review string configuration, MPPT "
                        "distribution, protection and mounting."
                    ),
                )
            )

    array_voltage = _positive(
        _first(
            selected,
            "array_voltage",
            "pv_array_voltage",
            default=_first(
                requirement,
                "array_voltage",
                default=None,
            ),
        )
    )

    array_current = _positive(
        _first(
            selected,
            "array_current",
            "pv_array_current",
            default=_first(
                requirement,
                "array_current",
                "minimum_pv_current",
                default=None,
            ),
        )
    )

    controller_requirement = (
        controller_result.get(
            "requirement",
            {}
        )
        if isinstance(
            controller_result,
            dict,
        )
        else {}
    )

    if not isinstance(
        controller_requirement,
        dict,
    ):
        controller_requirement = {}

    required_pv_voltage = _positive(
        _first(
            controller_requirement,
            "minimum_pv_voltage",
            "required_pv_voltage",
            default=None,
        )
    )

    if (
        array_voltage
        and
        required_pv_voltage
        and
        array_voltage < required_pv_voltage
    ):
        warnings.append(
            _warning(
                code="PV_VOLTAGE_BELOW_CONTROLLER_REQUIREMENT",
                severity=SEVERITY_CRITICAL,
                message=(
                    "The PV array voltage is below the charge "
                    "controller's required PV voltage."
                ),
                category="pv_controller",
                source=ENGINE_NAME,
                recommendation=(
                    "Review PV series string configuration."
                ),
            )
        )

    required_pv_current = _positive(
        _first(
            controller_requirement,
            "minimum_pv_current",
            "required_pv_current",
            default=None,
        )
    )

    if (
        array_current
        and
        required_pv_current
        and
        array_current < required_pv_current
    ):
        warnings.append(
            _warning(
                code="PV_CURRENT_BELOW_REQUIREMENT",
                severity=SEVERITY_ERROR,
                message=(
                    "The PV array current is below the "
                    "charge-controller requirement."
                ),
                category="pv_controller",
                source=ENGINE_NAME,
                recommendation=(
                    "Review PV parallel-string configuration."
                ),
            )
        )

    return warnings


# ======================================================================
# CONTROLLER VALIDATION
# ======================================================================

def _validate_controller(
    result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    requirement = result.get(
        "requirement",
        {},
    )

    selected = result.get(
        "selected",
        {},
    )

    if not isinstance(
        requirement,
        dict,
    ):
        requirement = {}

    if not isinstance(
        selected,
        dict,
    ):
        selected = {}

    required_power = _decimal(
        _first(
            requirement,
            "minimum_controller_power",
            "required_controller_power",
            default=ZERO,
        )
    )

    selected_power = _decimal(
        _first(
            selected,
            "power",
            "rated_power",
            "controller_power",
            "total_power",
            default=ZERO,
        )
    )

    if (
        required_power > ZERO
        and
        selected_power > ZERO
        and
        selected_power < required_power
    ):
        warnings.append(
            _warning(
                code="CONTROLLER_UNDERSIZED",
                severity=SEVERITY_CRITICAL,
                message=(
                    "Selected charge-controller capacity is "
                    "below the calculated requirement."
                ),
                category="controller",
                source=ENGINE_NAME,
                recommendation=(
                    "Increase controller capacity or use "
                    "multiple suitable controllers."
                ),
            )
        )

    return warnings


# ======================================================================
# INVERTER VALIDATION
# ======================================================================

def _validate_inverter(
    result: Dict[str, Any],
    load_result: Dict[str, Any],
    voltage_result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    requirement = result.get(
        "requirement",
        {},
    )

    selected = result.get(
        "selected",
        {},
    )

    if not isinstance(
        requirement,
        dict,
    ):
        requirement = {}

    if not isinstance(
        selected,
        dict,
    ):
        selected = {}

    required_power = _decimal(
        _first(
            requirement,
            "required_power_w",
            "minimum_power_w",
            "inverter_power_w",
            default=ZERO,
        )
    )

    selected_power = _decimal(
        _first(
            selected,
            "power_w",
            "rated_power_w",
            "capacity_w",
            "continuous_power_w",
            default=ZERO,
        )
    )

    if (
        required_power > ZERO
        and
        selected_power > ZERO
        and
        selected_power < required_power
    ):
        warnings.append(
            _warning(
                code="INVERTER_UNDERSIZED",
                severity=SEVERITY_CRITICAL,
                message=(
                    "Selected inverter continuous power is "
                    "below the calculated requirement."
                ),
                category="inverter",
                source=ENGINE_NAME,
                recommendation=(
                    "Select an inverter with sufficient "
                    "continuous output capacity."
                ),
            )
        )

    selected_surge = _decimal(
        _first(
            selected,
            "surge_power_w",
            "surge_capacity_w",
            "peak_power_w",
            default=ZERO,
        )
    )

    load_calculations = load_result.get(
        "calculations",
        {}
    )

    if not isinstance(
        load_calculations,
        dict,
    ):
        load_calculations = {}

    required_surge = _decimal(
        _first(
            load_calculations,
            "surge_peak_load_w",
            "peak_design_load_w",
            default=_first(
                load_result,
                "surge_watts",
                "surge_load_w",
                default=ZERO,
            ),
        )
    )

    if (
        required_surge > ZERO
        and
        selected_surge > ZERO
        and
        selected_surge < required_surge
    ):
        warnings.append(
            _warning(
                code="INVERTER_SURGE_INADEQUATE",
                severity=SEVERITY_ERROR,
                message=(
                    "The selected inverter surge capability is "
                    "below the calculated design surge demand."
                ),
                category="inverter",
                source=ENGINE_NAME,
                recommendation=(
                    "Verify motor/compressor starting demand "
                    "and inverter surge specifications."
                ),
            )
        )

    system_voltage = _first(
        voltage_result,
        "system_voltage",
        "selected_voltage",
        default=None,
    )

    inverter_voltage = _first(
        selected,
        "battery_voltage",
        "dc_voltage",
        "input_voltage",
        "nominal_voltage",
        default=None,
    )

    if (
        system_voltage is not None
        and
        inverter_voltage is not None
    ):
        system = _decimal(
            system_voltage
        )
        inverter = _decimal(
            inverter_voltage
        )

        if (
            system > ZERO
            and
            inverter > ZERO
            and
            system != inverter
        ):
            warnings.append(
                _warning(
                    code="INVERTER_DC_VOLTAGE_MISMATCH",
                    severity=SEVERITY_CRITICAL,
                    message=(
                        "The selected inverter DC voltage does "
                        "not match the selected system voltage."
                    ),
                    category="inverter",
                    source=ENGINE_NAME,
                    recommendation=(
                        "Verify inverter DC input voltage and "
                        "battery-system voltage compatibility."
                    ),
                )
            )

    return warnings


# ======================================================================
# PROTECTION VALIDATION
# ======================================================================

def _validate_protection(
    result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    requirement = result.get(
        "requirement",
        {},
    )

    if not isinstance(
        requirement,
        dict,
    ):
        requirement = {}

    expected_fields = (
        "system_voltage",
        "battery_current",
        "pv_array_current",
        "pv_array_voltage",
        "inverter_input_current",
    )

    missing = [
        field
        for field in expected_fields
        if _first(
            requirement,
            field,
            default=None,
        ) is None
    ]

    if missing:
        warnings.append(
            _warning(
                code="PROTECTION_REQUIREMENTS_INCOMPLETE",
                severity=SEVERITY_WARNING,
                message=(
                    "Some protection-engineering requirements "
                    "are missing."
                ),
                category="protection",
                source=ENGINE_NAME,
                recommendation=(
                    "Verify that all required protection devices "
                    "were evaluated before installation."
                ),
            )
        )

    return warnings


# ======================================================================
# CABLE VALIDATION
# ======================================================================

def _validate_cables(
    result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    if not isinstance(
        result,
        dict,
    ):
        return warnings

    requirement = result.get(
        "requirement",
        {},
    )

    if not isinstance(
        requirement,
        dict,
    ):
        requirement = {}

    required_fields = (
        "battery_current",
        "pv_current",
        "inverter_output_current",
    )

    missing = [
        field
        for field in required_fields
        if _first(
            requirement,
            field,
            default=None,
        ) is None
    ]

    if missing:
        warnings.append(
            _warning(
                code="CABLE_REQUIREMENTS_INCOMPLETE",
                severity=SEVERITY_WARNING,
                message=(
                    "One or more cable-engineering requirements "
                    "are missing."
                ),
                category="cable",
                source=ENGINE_NAME,
                recommendation=(
                    "Verify all DC, AC and earthing cable "
                    "requirements."
                ),
            )
        )

    return warnings


# ======================================================================
# BOQ VALIDATION
# ======================================================================

def _validate_boq(
    result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    if not isinstance(
        result,
        dict,
    ):
        return [
            _warning(
                code="BOQ_INVALID",
                severity=SEVERITY_CRITICAL,
                message="BOQ result is invalid.",
                category="boq",
                source=ENGINE_NAME,
            )
        ]

    items = _first(
        result,
        "items",
        "boq_items",
        "lines",
        default=None,
    )

    if items is None:
        items = _first(
            result.get(
                "boq",
                {}
            ),
            "items",
            "lines",
            default=None,
        )

    if items is not None:

        if not isinstance(
            items,
            (list, tuple),
        ):
            warnings.append(
                _warning(
                    code="BOQ_ITEMS_INVALID",
                    severity=SEVERITY_ERROR,
                    message=(
                        "BOQ items are not in a valid list format."
                    ),
                    category="boq",
                    source=ENGINE_NAME,
                )
            )

        elif not items:
            warnings.append(
                _warning(
                    code="BOQ_EMPTY",
                    severity=SEVERITY_CRITICAL,
                    message=(
                        "The bill of quantities contains no items."
                    ),
                    category="boq",
                    source=ENGINE_NAME,
                )
            )

    return warnings


# ======================================================================
# PRICING VALIDATION
# ======================================================================

def _validate_pricing(
    result: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    if not isinstance(
        result,
        dict,
    ):
        return [
            _warning(
                code="PRICING_INVALID",
                severity=SEVERITY_CRITICAL,
                message="Pricing result is invalid.",
                category="pricing",
                source=ENGINE_NAME,
            )
        ]

    grand_total = _decimal(
        _first(
            result,
            "grand_total",
            "total",
            "final_total",
            default=ZERO,
        )
    )

    if grand_total <= ZERO:
        warnings.append(
            _warning(
                code="PRICING_ZERO_TOTAL",
                severity=SEVERITY_ERROR,
                message=(
                    "The calculated project price is zero or "
                    "missing."
                ),
                category="pricing",
                source=ENGINE_NAME,
                recommendation=(
                    "Verify BOQ quantities and catalogue prices."
                ),
            )
        )

    return warnings


# ======================================================================
# CROSS-ENGINE VALIDATION
# ======================================================================

def _validate_cross_engine(
    results: Dict[str, Any],
) -> List[Dict[str, Any]]:

    warnings = []

    voltage_result = results.get(
        "voltage_result",
        {}
    )

    battery_result = results.get(
        "battery_result",
        {}
    )

    panel_result = results.get(
        "panel_result",
        {}
    )

    controller_result = results.get(
        "controller_result",
        {}
    )

    inverter_result = results.get(
        "inverter_result",
        {}
    )

    system_voltage = _positive(
        _first(
            voltage_result,
            "system_voltage",
            "selected_voltage",
            "recommended_system_voltage",
            default=None,
        )
    )

    if system_voltage:

        battery_system_voltage = _positive(
            _nested(
                battery_result,
                "requirement",
                "system_voltage",
                "nominal_system_voltage",
                default=None,
            )
        )

        if (
            battery_system_voltage
            and
            battery_system_voltage != system_voltage
        ):
            warnings.append(
                _warning(
                    code="VOLTAGE_BATTERY_ENGINE_MISMATCH",
                    severity=SEVERITY_CRITICAL,
                    message=(
                        "The system voltage selected by the "
                        "System Voltage Engine does not match "
                        "the voltage used by the Battery Engine."
                    ),
                    category="integration",
                    source=ENGINE_NAME,
                    recommendation=(
                        "Use one consistent system-voltage value "
                        "throughout the design pipeline."
                    ),
                )
            )

        inverter_system_voltage = _positive(
            _nested(
                inverter_result,
                "requirement",
                "system_voltage",
                "battery_voltage",
                "dc_voltage",
                default=None,
            )
        )

        if (
            inverter_system_voltage
            and
            inverter_system_voltage != system_voltage
        ):
            warnings.append(
                _warning(
                    code="VOLTAGE_INVERTER_ENGINE_MISMATCH",
                    severity=SEVERITY_CRITICAL,
                    message=(
                        "The inverter requirements use a system "
                        "voltage different from the selected "
                        "system voltage."
                    ),
                    category="integration",
                    source=ENGINE_NAME,
                    recommendation=(
                        "Verify the inverter DC-voltage "
                        "architecture."
                    ),
                )
            )

    # --------------------------------------------------------------
    # PV → CONTROLLER
    # --------------------------------------------------------------

    panel_power = _positive(
        _nested(
            panel_result,
            "selected",
            "array_power",
            "array_power_w",
            default=None,
        )
    )

    controller_required_power = _positive(
        _nested(
            controller_result,
            "requirement",
            "minimum_pv_power",
            "minimum_controller_power",
            default=None,
        )
    )

    if (
        panel_power
        and
        controller_required_power
        and
        panel_power < controller_required_power
    ):
        warnings.append(
            _warning(
                code="PV_CONTROLLER_POWER_MISMATCH",
                severity=SEVERITY_ERROR,
                message=(
                    "The selected PV array does not satisfy "
                    "the charge-controller engineering requirement."
                ),
                category="integration",
                source=ENGINE_NAME,
                recommendation=(
                    "Review PV array size and controller capacity."
                ),
            )
        )

    return warnings


# ======================================================================
# DEDUPLICATION
# ======================================================================

def _deduplicate(
    warnings: Iterable[Dict[str, Any]],
) -> List[Dict[str, Any]]:
    """Remove duplicate warnings while preserving order."""

    result = []
    seen = set()

    for item in warnings:

        key = (
            item.get("code"),
            item.get("severity"),
            item.get("message"),
        )

        if key in seen:
            continue

        seen.add(key)
        result.append(item)

    return result


# ======================================================================
# SUMMARY
# ======================================================================

def _build_summary(
    warnings: List[Dict[str, Any]],
) -> Dict[str, Any]:

    summary = {
        "total": len(warnings),
        "critical": 0,
        "error": 0,
        "warning": 0,
        "advisory": 0,
        "info": 0,
    }

    for item in warnings:

        severity = item.get(
            "severity",
            SEVERITY_WARNING,
        )

        if severity in summary:
            summary[severity] += 1

    summary["blocking"] = (
        summary["critical"]
        +
        summary["error"]
    )

    summary["requires_attention"] = (
        summary["blocking"]
        +
        summary["warning"]
    )

    return summary


# ======================================================================
# FINAL STATUS
# ======================================================================

def _final_status(
    summary: Dict[str, Any],
) -> str:

    if summary["critical"] > 0:
        return "critical"

    if summary["error"] > 0:
        return "not_ready"

    if summary["warning"] > 0:
        return "review"

    if summary["advisory"] > 0:
        return "acceptable_with_advisories"

    return "ready"


# ======================================================================
# MAIN ENGINE
# ======================================================================

def validate_design(
    *,
    load_result: Dict[str, Any],
    voltage_result: Dict[str, Any],
    battery_result: Dict[str, Any],
    panel_result: Dict[str, Any],
    controller_result: Dict[str, Any],
    inverter_result: Dict[str, Any],
    protection_result: Dict[str, Any],
    cable_result: Dict[str, Any],
    accessory_result: Dict[str, Any],
    boq_result: Dict[str, Any],
    pricing_result: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Perform final design warnings and cross-engine validation.

    All preceding engine results are passed explicitly.

    Returns a stable result dictionary suitable for:

        - views
        - templates
        - JSON
        - SolarDesign JSONField
        - PDF/report generation
        - final design orchestration
    """

    results = {
        "load_result": load_result,
        "voltage_result": voltage_result,
        "battery_result": battery_result,
        "panel_result": panel_result,
        "controller_result": controller_result,
        "inverter_result": inverter_result,
        "protection_result": protection_result,
        "cable_result": cable_result,
        "accessory_result": accessory_result,
        "boq_result": boq_result,
        "pricing_result": pricing_result,
    }

    warnings: List[Dict[str, Any]] = []

    # --------------------------------------------------------------
    # UPSTREAM WARNINGS
    # --------------------------------------------------------------

    warnings.extend(
        _collect_upstream_warnings(
            results
        )
    )

    # --------------------------------------------------------------
    # PIPELINE VALIDATION
    # --------------------------------------------------------------

    warnings.extend(
        _validate_stage_results(
            results
        )
    )

    # --------------------------------------------------------------
    # ENGINE-SPECIFIC VALIDATION
    # --------------------------------------------------------------

    warnings.extend(
        _validate_load(
            load_result
        )
    )

    warnings.extend(
        _validate_voltage(
            voltage_result,
            battery_result,
        )
    )

    warnings.extend(
        _validate_battery(
            battery_result
        )
    )

    warnings.extend(
        _validate_panel(
            panel_result,
            controller_result,
        )
    )

    warnings.extend(
        _validate_controller(
            controller_result
        )
    )

    warnings.extend(
        _validate_inverter(
            inverter_result,
            load_result,
            voltage_result,
        )
    )

    warnings.extend(
        _validate_protection(
            protection_result
        )
    )

    warnings.extend(
        _validate_cables(
            cable_result
        )
    )

    warnings.extend(
        _validate_boq(
            boq_result
        )
    )

    warnings.extend(
        _validate_pricing(
            pricing_result
        )
    )

    # --------------------------------------------------------------
    # CROSS-ENGINE VALIDATION
    # --------------------------------------------------------------

    warnings.extend(
        _validate_cross_engine(
            results
        )
    )

    # --------------------------------------------------------------
    # DEDUPLICATE
    # --------------------------------------------------------------

    warnings = _deduplicate(
        warnings
    )

    # --------------------------------------------------------------
    # SUMMARY
    # --------------------------------------------------------------

    summary = _build_summary(
        warnings
    )

    status = _final_status(
        summary
    )

    # --------------------------------------------------------------
    # FINAL RESULT
    # --------------------------------------------------------------

    success = status not in {
        "critical",
        "not_ready",
    }

    return {
        "success": success,
        "status": status,

        "ready_for_final_design": (
            status == "ready"
            or
            status == "acceptable_with_advisories"
        ),

        "summary": summary,

        "warnings": warnings,

        "critical_warnings": [
            item
            for item in warnings
            if item["severity"]
            == SEVERITY_CRITICAL
        ],

        "errors": [
            item
            for item in warnings
            if item["severity"]
            == SEVERITY_ERROR
        ],

        "review_warnings": [
            item
            for item in warnings
            if item["severity"]
            == SEVERITY_WARNING
        ],

        "advisories": [
            item
            for item in warnings
            if item["severity"]
            == SEVERITY_ADVISORY
        ],

        "messages": [
            (
                "Final engineering validation completed."
            ),
            (
                f"Design validation status: {status}."
            ),
        ],

        "message": (
            "Design validation completed successfully."
            if success
            else
            "Design validation identified issues "
            "that require attention."
        ),

        "engine": ENGINE_NAME,
        "engine_version": ENGINE_VERSION,
    }


# ======================================================================
# SIMPLE PUBLIC API
# ======================================================================

def calculate_warnings(
    *,
    load_result: Dict[str, Any],
    voltage_result: Dict[str, Any],
    battery_result: Dict[str, Any],
    panel_result: Dict[str, Any],
    controller_result: Dict[str, Any],
    inverter_result: Dict[str, Any],
    protection_result: Dict[str, Any],
    cable_result: Dict[str, Any],
    accessory_result: Dict[str, Any],
    boq_result: Dict[str, Any],
    pricing_result: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Public functional API.

    This is the function the future design orchestration layer
    should call.
    """

    return validate_design(
        load_result=load_result,
        voltage_result=voltage_result,
        battery_result=battery_result,
        panel_result=panel_result,
        controller_result=controller_result,
        inverter_result=inverter_result,
        protection_result=protection_result,
        cable_result=cable_result,
        accessory_result=accessory_result,
        boq_result=boq_result,
        pricing_result=pricing_result,
    )


# ======================================================================
# PUBLIC ALIAS
# ======================================================================

build_warnings = calculate_warnings